order_new <- c("Bulksoil_before_sowing_NK_19_Soil",
                  "Bulksoil_before_sowing_NPK_23_Soil",
                  "Bulksoil_before_sowing_CONMIN_96_Soil",
                  "Bulksoil_before_sowing_CONMIN_56_Soil",
                  "Bulksoil_before_sowing_CONMIN_6_Soil",
                  "Bulksoil_before_sowing_BIODYN_90_Soil",
                  "Bulksoil_before_sowing_BIODYN_50_Soil",
                  "Bulksoil_before_sowing_BIODYN_12_Soil",
                  "Bulksoil_Vegetative_NK_19_Soil",
                  "Bulksoil_Vegetative_NPK_23_Soil",
                  "Bulksoil_Vegetative_CONMIN_96_Soil",
                  "Bulksoil_Vegetative_CONMIN_56_Soil",
                  "Bulksoil_Vegetative_CONMIN_6_Soil",
                  "Bulksoil_Vegetative_BIODYN_90_Soil",
                  "Bulksoil_Vegetative_BIODYN_50_Soil",
                  "Bulksoil_Vegetative_BIODYN_12_Soil",
                  "Bulksoil_Reproductive_NK_19_Soil",
                  "Bulksoil_Reproductive_NPK_23_Soil",
                  "Bulksoil_Reproductive_CONMIN_96_Soil",
                  "Bulksoil_Reproductive_CONMIN_56_Soil",
                  "Bulksoil_Reproductive_CONMIN_6_Soil",
                  "Bulksoil_Reproductive_BIODYN_90_Soil",
                  "Bulksoil_Reproductive_BIODYN_50_Soil",
                  "Bulksoil_Reproductive_BIODYN_12_Soil",
                  "Rhizosphere_Vegetative_NK_19_1_B73",
                  "Rhizosphere_Vegetative_NK_19_2_DK105",
                  "Rhizosphere_Vegetative_NK_19_3_PH207",
                  "Rhizosphere_Vegetative_NK_19_4_F2",
                  "Rhizosphere_Vegetative_NK_19_5_pht1;6",
                  "Rhizosphere_Vegetative_NPK_23_1_B73",
                  "Rhizosphere_Vegetative_NPK_23_2_DK105",
                  "Rhizosphere_Vegetative_NPK_23_3_PH207",
                  "Rhizosphere_Vegetative_NPK_23_4_F2",
                  "Rhizosphere_Vegetative_NPK_23_5_pht1;6",
                  "Rhizosphere_Vegetative_CONMIN_96_1_B73",
                  "Rhizosphere_Vegetative_CONMIN_96_2_DK105",
                  "Rhizosphere_Vegetative_CONMIN_96_3_PH207",
                  "Rhizosphere_Vegetative_CONMIN_96_4_F2",
                  "Rhizosphere_Vegetative_CONMIN_96_5_pht1;6",
                  "Rhizosphere_Vegetative_CONMIN_56_1_B73",
                  "Rhizosphere_Vegetative_CONMIN_56_2_DK105",
                  "Rhizosphere_Vegetative_CONMIN_56_3_PH207",
                  "Rhizosphere_Vegetative_CONMIN_56_4_F2",
                  "Rhizosphere_Vegetative_CONMIN_56_5_pht1;6",
                  "Rhizosphere_Vegetative_CONMIN_6_1_B73",
                  "Rhizosphere_Vegetative_CONMIN_6_2_DK105",
                  "Rhizosphere_Vegetative_CONMIN_6_3_PH207",
                  "Rhizosphere_Vegetative_CONMIN_6_4_F2",
                  "Rhizosphere_Vegetative_CONMIN_6_5_pht1;6",
                  "Rhizosphere_Vegetative_BIODYN_90_1_B73",
                  "Rhizosphere_Vegetative_BIODYN_90_2_DK105",
                  "Rhizosphere_Vegetative_BIODYN_90_3_PH207",
                  "Rhizosphere_Vegetative_BIODYN_90_4_F2",
                  "Rhizosphere_Vegetative_BIODYN_90_5_pht1;6",
                  "Rhizosphere_Vegetative_BIODYN_50_1_B73",
                  "Rhizosphere_Vegetative_BIODYN_50_2_DK105",
                  "Rhizosphere_Vegetative_BIODYN_50_3_PH207",
                  "Rhizosphere_Vegetative_BIODYN_50_4_F2",
                  "Rhizosphere_Vegetative_BIODYN_50_5_pht1;6",
                  "Rhizosphere_Vegetative_BIODYN_12_1_B73",
                  "Rhizosphere_Vegetative_BIODYN_12_2_DK105",
                  "Rhizosphere_Vegetative_BIODYN_12_3_PH207",
                  "Rhizosphere_Vegetative_BIODYN_12_4_F2",
                  "Rhizosphere_Vegetative_BIODYN_12_5_pht1;6",
                  "Rhizosphere_Reproductive_NK_19_1_B73",
                  "Rhizosphere_Reproductive_NK_19_2_DK105",
                  "Rhizosphere_Reproductive_NK_19_3_PH207",
                  "Rhizosphere_Reproductive_NK_19_4_F2",
                  "Rhizosphere_Reproductive_NK_19_5_pht1;6",
                  "Rhizosphere_Reproductive_NPK_23_1_B73",
                  "Rhizosphere_Reproductive_NPK_23_2_DK105",
                  "Rhizosphere_Reproductive_NPK_23_3_PH207",
                  "Rhizosphere_Reproductive_NPK_23_4_F2",
                  "Rhizosphere_Reproductive_NPK_23_5_pht1;6",
                  "Rhizosphere_Reproductive_CONMIN_96_1_B73",
                  "Rhizosphere_Reproductive_CONMIN_96_2_DK105",
                  "Rhizosphere_Reproductive_CONMIN_96_3_PH207",
                  "Rhizosphere_Reproductive_CONMIN_96_4_F2",
                  "Rhizosphere_Reproductive_CONMIN_96_5_pht1;6",
                  "Rhizosphere_Reproductive_CONMIN_56_1_B73",
                  "Rhizosphere_Reproductive_CONMIN_56_2_DK105",
                  "Rhizosphere_Reproductive_CONMIN_56_3_PH207",
                  "Rhizosphere_Reproductive_CONMIN_56_4_F2",
                  "Rhizosphere_Reproductive_CONMIN_56_5_pht1;6",
                  "Rhizosphere_Reproductive_CONMIN_6_1_B73",
                  "Rhizosphere_Reproductive_CONMIN_6_2_DK105",
                  "Rhizosphere_Reproductive_CONMIN_6_3_PH207",
                  "Rhizosphere_Reproductive_CONMIN_6_4_F2",
                  "Rhizosphere_Reproductive_CONMIN_6_5_pht1;6",
                  "Rhizosphere_Reproductive_BIODYN_90_1_B73",
                  "Rhizosphere_Reproductive_BIODYN_90_2_DK105",
                  "Rhizosphere_Reproductive_BIODYN_90_3_PH207",
                  "Rhizosphere_Reproductive_BIODYN_90_4_F2",
                  "Rhizosphere_Reproductive_BIODYN_90_5_pht1;6",
                  "Rhizosphere_Reproductive_BIODYN_50_1_B73",
                  "Rhizosphere_Reproductive_BIODYN_50_2_DK105",
                  "Rhizosphere_Reproductive_BIODYN_50_3_PH207",
                  "Rhizosphere_Reproductive_BIODYN_50_4_F2",
                  "Rhizosphere_Reproductive_BIODYN_50_5_pht1;6",
                  "Rhizosphere_Reproductive_BIODYN_12_1_B73",
                  "Rhizosphere_Reproductive_BIODYN_12_2_DK105",
                  "Rhizosphere_Reproductive_BIODYN_12_3_PH207",
                  "Rhizosphere_Reproductive_BIODYN_12_4_F2",
                  "Rhizosphere_Reproductive_BIODYN_12_5_pht1;6",
                  "Root_Vegetative_NK_19_1_B73",
                  "Root_Vegetative_NK_19_2_DK105",
                  "Root_Vegetative_NK_19_3_PH207",
                  "Root_Vegetative_NK_19_4_F2",
                  "Root_Vegetative_NK_19_5_pht1;6",
                  "Root_Vegetative_NPK_23_1_B73",
                  "Root_Vegetative_NPK_23_2_DK105",
                  "Root_Vegetative_NPK_23_3_PH207",
                  "Root_Vegetative_NPK_23_4_F2",
                  "Root_Vegetative_NPK_23_5_pht1;6",
                  "Root_Vegetative_CONMIN_96_1_B73",
                  "Root_Vegetative_CONMIN_96_2_DK105",
                  "Root_Vegetative_CONMIN_96_3_PH207",
                  "Root_Vegetative_CONMIN_96_4_F2",
                  "Root_Vegetative_CONMIN_96_5_pht1;6",
                  "Root_Vegetative_CONMIN_56_1_B73",
                  "Root_Vegetative_CONMIN_56_2_DK105",
                  "Root_Vegetative_CONMIN_56_3_PH207",
                  "Root_Vegetative_CONMIN_56_4_F2",
                  "Root_Vegetative_CONMIN_56_5_pht1;6",
                  "Root_Vegetative_CONMIN_6_1_B73",
                  "Root_Vegetative_CONMIN_6_2_DK105",
                  "Root_Vegetative_CONMIN_6_3_PH207",
                  "Root_Vegetative_CONMIN_6_4_F2",
                  "Root_Vegetative_CONMIN_6_5_pht1;6",
                  "Root_Vegetative_BIODYN_90_1_B73",
                  "Root_Vegetative_BIODYN_90_2_DK105",
                  "Root_Vegetative_BIODYN_90_3_PH207",
                  "Root_Vegetative_BIODYN_90_4_F2",
                  "Root_Vegetative_BIODYN_90_5_pht1;6",
                  "Root_Vegetative_BIODYN_50_1_B73",
                  "Root_Vegetative_BIODYN_50_2_DK105",
                  "Root_Vegetative_BIODYN_50_3_PH207",
                  "Root_Vegetative_BIODYN_50_4_F2",
                  "Root_Vegetative_BIODYN_50_5_pht1;6",
                  "Root_Vegetative_BIODYN_12_1_B73",
                  "Root_Vegetative_BIODYN_12_2_DK105",
                  "Root_Vegetative_BIODYN_12_3_PH207",
                  "Root_Vegetative_BIODYN_12_4_F2",
                  "Root_Vegetative_BIODYN_12_5_pht1;6",
                  "Root_Reproductive_NK_19_1_B73",
                  "Root_Reproductive_NK_19_2_DK105",
                  "Root_Reproductive_NK_19_3_PH207",
                  "Root_Reproductive_NK_19_4_F2",
                  "Root_Reproductive_NK_19_5_pht1;6",
                  "Root_Reproductive_NPK_23_1_B73",
                  "Root_Reproductive_NPK_23_2_DK105",
                  "Root_Reproductive_NPK_23_3_PH207",
                  "Root_Reproductive_NPK_23_4_F2",
                  "Root_Reproductive_NPK_23_5_pht1;6",
                  "Root_Reproductive_CONMIN_96_1_B73",
                  "Root_Reproductive_CONMIN_96_2_DK105",
                  "Root_Reproductive_CONMIN_96_3_PH207",
                  "Root_Reproductive_CONMIN_96_4_F2",
                  "Root_Reproductive_CONMIN_96_5_pht1;6",
                  "Root_Reproductive_CONMIN_56_1_B73",
                  "Root_Reproductive_CONMIN_56_2_DK105",
                  "Root_Reproductive_CONMIN_56_3_PH207",
                  "Root_Reproductive_CONMIN_56_4_F2",
                  "Root_Reproductive_CONMIN_56_5_pht1;6",
                  "Root_Reproductive_CONMIN_6_1_B73",
                  "Root_Reproductive_CONMIN_6_2_DK105",
                  "Root_Reproductive_CONMIN_6_3_PH207",
                  "Root_Reproductive_CONMIN_6_4_F2",
                  "Root_Reproductive_CONMIN_6_5_pht1;6",
                  "Root_Reproductive_BIODYN_90_1_B73",
                  "Root_Reproductive_BIODYN_90_2_DK105",
                  "Root_Reproductive_BIODYN_90_3_PH207",
                  "Root_Reproductive_BIODYN_90_4_F2",
                  "Root_Reproductive_BIODYN_90_5_pht1;6",
                  "Root_Reproductive_BIODYN_50_1_B73",
                  "Root_Reproductive_BIODYN_50_2_DK105",
                  "Root_Reproductive_BIODYN_50_3_PH207",
                  "Root_Reproductive_BIODYN_50_4_F2",
                  "Root_Reproductive_BIODYN_50_5_pht1;6",
                  "Root_Reproductive_BIODYN_12_1_B73",
                  "Root_Reproductive_BIODYN_12_2_DK105",
                  "Root_Reproductive_BIODYN_12_3_PH207",
                  "Root_Reproductive_BIODYN_12_4_F2",
                  "Root_Reproductive_BIODYN_12_5_pht1;6")
###############################################################################
Bac_phyla <- c("Acidobacteria", "Actinobacteria", "Bacteroidetes",
               "Firmicutes",
               "Alphaproteobacteria", "Betaproteobacteria",
               "Gammaproteobacteria", "Deltaproteobacteria",
               "Chloroflexi","Gemmatimonadetes",
               "Planctomycetes","Verrucomicrobia")

Bac_phyla_2 <- c(Bac_phyla, "Others", "Unassigned")

c_Bac <- data.frame(group = Bac_phyla_2,
                    color = c("coral2", "chocolate4", c_bacteroi, "royalblue",
                              c_dark_green, c_green, c_sea_green, "darkgreen",
                              "gold2", c_grey, c_pink,
                              "darkgoldenrod4", "darkorange", "slategrey")
                    )

c_Bac$group <- factor(c_Bac$group, levels = Bac_phyla_2, ordered = TRUE)

###############################################################################

Fun_phyla <- c("p__Aphelidiomycota", "p__Ascomycota",
               "p__Basidiomycota", "p__Basidiobolomycota",
               "p__Chytridiomycota", "p__Calcarisporiellomycota",
               "p__Entomophthoromycota",
               "p__Glomeromycota",
               "p__Kickxellomycota",
               "p__Mucoromycota", "p__Monoblepharomycota",
               "p__Mortierellomycota",
               "p__Olpidiomycota",
               "p__Zoopagomycota", "p__Rozellomycota")

Fun_phyla_2 <- c(Fun_phyla, "Others", "Unassigned")

set_fungi <- c(brewer.pal(n = 9, name = "Set1")[c(4, 7, 5, 8, 9)],
               brewer.pal(n = 8, name = "Dark2")[c(1, 3 : 8)],
               brewer.pal(n = 8, name = "Accent")[1 : 5])

c_Fun <- data.frame(group = Fun_phyla_2, color = set_fungi)
c_Fun$group <- factor(c_Fun$group, levels = Fun_phyla_2, ordered = TRUE)
